### ISSUE TITLE
next difficulty retarget calc for bitcoin blockchain

### ISSUE THREAD

**Issue by mahalamobile** [zack-bitcoin/basiccoin#44]
Hi, i came across your project. Im looking for code for a predictive estimate on the next regart for bitcoin. any ideas? i do agree that its more accurate to literally check every second for a new block then go back historically to get the average time over the last say 100 blocks and then also last blocks since the last retarget. obviously any scheme used will become the "most" accurate as we tend towards the actual retarget date/time. Any code and or API will be greatly appreciated. this is actually for an academic paper :/0 thanks again neil

**Comment by zack-bitcoin** [comment]
Preduction the next difficulty on bitcoin is easy. Just look at how quickly mining is happening since the last retarget. Bitcoin retarget every 2000th block.
Maybe I don't understand your question.
